using Eu.Iamia.Invoicing.E_Conomic.RestApiGateway.Contract;
using Eu.Iamia.Utils.Contract;
using System.Text;

namespace Eu.Iamia.Invoicing.Application.UnitTests;
public class RestApiGatewayStub : IRestApiGateway
{
    public async Task<Stream> GetCustomers(int skipPages, int pageSize, CancellationToken cancellationToken)
    {
        const string response = "{\"collection\":[{\"customerNumber\":99999,\"currency\":\"DKK\",\"paymentTerms\":{\"paymentTermsNumber\":4,\"self\":\"https://restapi.e-conomic.com/payment-terms/4\"},\"customerGroup\":{\"customerGroupNumber\":1,\"self\":\"https://restapi.e-conomic.com/customer-groups/1\"},\"address\":\"Dette er en testkunde.\",\"balance\":0.0,\"dueAmount\":0.00,\"email\":\"dyssekilde@gmail.com\",\"name\":\"Testkunde\",\"vatZone\":{\"vatZoneNumber\":1,\"self\":\"https://restapi.e-conomic.com/vat-zones/1\"},\"lastUpdated\":\"2024-06-11T11:19:28Z\",\"contacts\":\"https://restapi.e-conomic.com/customers/99999/contacts\",\"templates\":{\"invoice\":\"https://restapi.e-conomic.com/customers/99999/templates/invoice\",\"invoiceLine\":\"https://restapi.e-conomic.com/customers/99999/templates/invoiceline\",\"self\":\"https://restapi.e-conomic.com/customers/99999/templates\"},\"totals\":{\"drafts\":\"https://restapi.e-conomic.com/invoices/totals/drafts/customers/99999\",\"booked\":\"https://restapi.e-conomic.com/invoices/totals/booked/customers/99999\",\"self\":\"https://restapi.e-conomic.com/customers/99999/totals\"},\"deliveryLocations\":\"https://restapi.e-conomic.com/customers/99999/delivery-locations\",\"invoices\":{\"drafts\":\"https://restapi.e-conomic.com/customers/99999/invoices/drafts\",\"booked\":\"https://restapi.e-conomic.com/customers/99999/invoices/booked\",\"self\":\"https://restapi.e-conomic.com/customers/99999/invoices\"},\"eInvoicingDisabledByDefault\":false,\"self\":\"https://restapi.e-conomic.com/customers/99999\"}],\"pagination\":{\"skipPages\":1,\"pageSize\":278,\"maxPageSizeAllowed\":1000,\"results\":279,\"resultsWithoutFilter\":279,\"firstPage\":\"https://restapi.e-conomic.com/customers?skippages=0&pagesize=278\",\"previousPage\":\"https://restapi.e-conomic.com/customers?skippages=0&pagesize=278\",\"lastPage\":\"https://restapi.e-conomic.com/customers?skippages=1&pagesize=278\"},\"metaData\":{\"create\":{\"description\":\"Create a new customer\",\"href\":\"https://restapi.e-conomic.com/customers?skippages=1&pagesize=278\",\"httpMethod\":\"post\"}},\"self\":\"https://restapi.e-conomic.com/customers?skippages=1&pagesize=278\"}";
        return new MemoryStream(Encoding.UTF8.GetBytes(response));
    }

    public async Task<Stream> GetDraftInvoices(int skipPages, int pageSize, CancellationToken cancellationToken)
    {
        const string response = "{\"collection\":[" +
                                "{\"draftInvoiceNumber\":454,\"soap\":{\"currentInvoiceHandle\":{\"id\":34}},\"templates\":{\"bookingInstructions\":\"https://restapi.e-conomic.com/invoices/drafts/454/templates/booking-instructions\",\"self\":\"https://restapi.e-conomic.com/invoices/drafts/454/templates\"},\"attachment\":\"https://restapi.e-conomic.com/invoices/drafts/454/attachment\",\"date\":\"2023-03-24\",\"currency\":\"DKK\",\"exchangeRate\":100.000000,\"netAmount\":5089.770000,\"netAmountInBaseCurrency\":5089.77,\"grossAmount\":5089.770000,\"grossAmountInBaseCurrency\":5089.77,\"marginInBaseCurrency\":5089.7700,\"marginPercentage\":100.00,\"vatAmount\":0.000000,\"roundingAmount\":0.00,\"costPriceInBaseCurrency\":0.0000,\"dueDate\":\"2023-04-14\",\"paymentTerms\":{\"paymentTermsNumber\":1,\"daysOfCredit\":14,\"name\":\"Lb. md. 14 dage\",\"paymentTermsType\":\"invoiceMonth\",\"self\":\"https://restapi.e-conomic.com/payment-terms/1\"},\"customer\":{\"customerNumber\":7,\"self\":\"https://restapi.e-conomic.com/customers/7\"},\"recipient\":{\"name\":\"Tommy Werge\",\"address\":\"Månen 5\",\"zip\":\"3390\",\"city\":\"Hundested\",\"vatZone\":{\"name\":\"Domestic\",\"vatZoneNumber\":1,\"enabledForCustomer\":true,\"enabledForSupplier\":true,\"self\":\"https://restapi.e-conomic.com/vat-zones/1\"}},\"notes\":{\"heading\":\"#7 Tommy Werge\",\"textLine1\":\"ØD fakturering for 2024\"},\"layout\":{\"layoutNumber\":21,\"self\":\"https://restapi.e-conomic.com/layouts/21\"},\"pdf\":{\"download\":\"https://restapi.e-conomic.com/invoices/drafts/454/pdf\"},\"lastUpdated\":\"2024-08-30T19:09:00Z\",\"self\":\"https://restapi.e-conomic.com/invoices/drafts/454\"}," +
                                "{\"draftInvoiceNumber\":485,\"soap\":{\"currentInvoiceHandle\":{\"id\":35}},\"templates\":{\"bookingInstructions\":\"https://restapi.e-conomic.com/invoices/drafts/485/templates/booking-instructions\",\"self\":\"https://restapi.e-conomic.com/invoices/drafts/485/templates\"},\"attachment\":\"https://restapi.e-conomic.com/invoices/drafts/485/attachment\",\"date\":\"2024-09-09\",\"currency\":\"DKK\",\"exchangeRate\":100.000000,\"netAmount\":1.000000,\"netAmountInBaseCurrency\":1.00,\"grossAmount\":1.000000,\"grossAmountInBaseCurrency\":1.00,\"marginInBaseCurrency\":1.0000,\"marginPercentage\":100.00,\"vatAmount\":0.000000,\"roundingAmount\":0.00,\"costPriceInBaseCurrency\":0.0000,\"dueDate\":\"2024-09-10\",\"paymentTerms\":{\"paymentTermsNumber\":4,\"daysOfCredit\":1,\"description\":\"Test betalings betingelse\",\"name\":\"99999\",\"paymentTermsType\":\"net\",\"self\":\"https://restapi.e-conomic.com/payment-terms/4\"},\"customer\":{\"customerNumber\":99999,\"self\":\"https://restapi.e-conomic.com/customers/99999\"},\"recipient\":{\"name\":\"Testkunde\",\"address\":\"Dette er en testkunde.\",\"zip\":\"\",\"city\":\"\",\"vatZone\":{\"name\":\"Domestic\",\"vatZoneNumber\":1,\"enabledForCustomer\":true,\"enabledForSupplier\":true,\"self\":\"https://restapi.e-conomic.com/vat-zones/1\"}},\"notes\":{\"heading\":\"#99999 Testkunde\",\"textLine1\":\"xx\"},\"layout\":{\"layoutNumber\":21,\"self\":\"https://restapi.e-conomic.com/layouts/21\"},\"pdf\":{\"download\":\"https://restapi.e-conomic.com/invoices/drafts/485/pdf\"},\"lastUpdated\":\"2024-09-09T20:24:00Z\",\"self\":\"https://restapi.e-conomic.com/invoices/drafts/485\"}]" +
                                ",\"pagination\":{\"skipPages\":0,\"pageSize\":2,\"maxPageSizeAllowed\":1000,\"results\":20,\"resultsWithoutFilter\":20,\"firstPage\":\"https://restapi.e-conomic.com/invoices/drafts?skippages=0&pagesize=2\",\"nextPage\":\"https://restapi.e-conomic.com/invoices/drafts?skippages=1&pagesize=2\",\"lastPage\":\"https://restapi.e-conomic.com/invoices/drafts?skippages=9&pagesize=2\"},\"self\":\"https://restapi.e-conomic.com/invoices/drafts?skippages=0&pagesize=2\"}";
        return new MemoryStream(Encoding.UTF8.GetBytes(response));
    }

    public async Task<Stream> GetDraftInvoice(int invoiceNumber, CancellationToken cancellationToken)
    {
        const string response454 = "{\"draftInvoiceNumber\":454,\"soap\":{\"currentInvoiceHandle\":{\"id\":34}},\"templates\":{\"bookingInstructions\":\"https://restapi.e-conomic.com/invoices/drafts/454/templates/booking-instructions\",\"self\":\"https://restapi.e-conomic.com/invoices/drafts/454/templates\"},\"attachment\":\"https://restapi.e-conomic.com/invoices/drafts/454/attachment\",\"lines\":[" +
                                   "{\"lineNumber\":1,\"sortKey\":1,\"description\":\"Grundejerforening\",\"unit\":{\"unitNumber\":3,\"name\":\"m2\",\"products\":\"https://restapi.e-conomic.com/units/3/products\",\"self\":\"https://restapi.e-conomic.com/units/3\"},\"product\":{\"productNumber\":\"3\",\"self\":\"https://restapi.e-conomic.com/products/3\"},\"quantity\":77.00,\"unitNetPrice\":6.00,\"discountPercentage\":0.00,\"unitCostPrice\":0.00,\"totalNetAmount\":462.00,\"marginInBaseCurrency\":462.00,\"marginPercentage\":100.00}," +
                                   "{\"lineNumber\":2,\"sortKey\":2,\"description\":\"Medlemskontingent\",\"unit\":{\"unitNumber\":1,\"name\":\"mdr\",\"products\":\"https://restapi.e-conomic.com/units/1/products\",\"self\":\"https://restapi.e-conomic.com/units/1\"},\"product\":{\"productNumber\":\"2\",\"self\":\"https://restapi.e-conomic.com/products/2\"},\"quantity\":1.00,\"unitNetPrice\":3000.00,\"discountPercentage\":0.00,\"unitCostPrice\":0.00,\"totalNetAmount\":3000.00,\"marginInBaseCurrency\":3000.00,\"marginPercentage\":100.00}," +
                                   "{\"lineNumber\":3,\"sortKey\":3,\"description\":\"Vandafledning (2023)\",\"unit\":{\"unitNumber\":5,\"name\":\"m3\",\"products\":\"https://restapi.e-conomic.com/units/5/products\",\"self\":\"https://restapi.e-conomic.com/units/5\"},\"product\":{\"productNumber\":\"4\",\"self\":\"https://restapi.e-conomic.com/products/4\"},\"quantity\":29.00,\"unitNetPrice\":56.13,\"discountPercentage\":0.00,\"unitCostPrice\":0.00,\"totalNetAmount\":1627.77,\"marginInBaseCurrency\":1627.77,\"marginPercentage\":100.00}]," +
                                   "\"date\":\"2023-03-24\",\"currency\":\"DKK\",\"exchangeRate\":100.000000,\"netAmount\":5089.770000,\"netAmountInBaseCurrency\":5089.77,\"grossAmount\":5089.770000,\"grossAmountInBaseCurrency\":5089.77,\"marginInBaseCurrency\":5089.7700,\"marginPercentage\":100.00,\"vatAmount\":0.000000,\"roundingAmount\":0.00,\"costPriceInBaseCurrency\":0.0000,\"dueDate\":\"2023-04-14\",\"paymentTerms\":{\"paymentTermsNumber\":1,\"daysOfCredit\":14,\"name\":\"Lb. md. 14 dage\",\"paymentTermsType\":\"invoiceMonth\",\"self\":\"https://restapi.e-conomic.com/payment-terms/1\"},\"customer\":{\"customerNumber\":7,\"self\":\"https://restapi.e-conomic.com/customers/7\"},\"recipient\":{\"name\":\"Tommy Werge\",\"address\":\"Månen 5\",\"zip\":\"3390\",\"city\":\"Hundested\",\"vatZone\":{\"name\":\"Domestic\",\"vatZoneNumber\":1,\"enabledForCustomer\":true,\"enabledForSupplier\":true,\"self\":\"https://restapi.e-conomic.com/vat-zones/1\"}},\"notes\":{\"heading\":\"#7 Tommy Werge\",\"textLine1\":\"ØD fakturering for 2024\"},\"layout\":{\"layoutNumber\":21,\"self\":\"https://restapi.e-conomic.com/layouts/21\"},\"pdf\":{\"download\":\"https://restapi.e-conomic.com/invoices/drafts/454/pdf\"},\"lastUpdated\":\"2024-08-30T19:09:00Z\",\"self\":\"https://restapi.e-conomic.com/invoices/drafts/454\"}";
        const string response485 = "{\"draftInvoiceNumber\":485,\"soap\":{\"currentInvoiceHandle\":{\"id\":35}},\"templates\":{\"bookingInstructions\":\"https://restapi.e-conomic.com/invoices/drafts/485/templates/booking-instructions\",\"self\":\"https://restapi.e-conomic.com/invoices/drafts/485/templates\"},\"attachment\":\"https://restapi.e-conomic.com/invoices/drafts/485/attachment\",\"lines\":[" +
                                   "{\"lineNumber\":1,\"sortKey\":1,\"description\":\"TestLine\",\"unit\":{\"unitNumber\":1,\"name\":\"mdr\",\"products\":\"https://restapi.e-conomic.com/units/1/products\",\"self\":\"https://restapi.e-conomic.com/units/1\"},\"product\":{\"productNumber\":\"99999\",\"self\":\"https://restapi.e-conomic.com/products/99999\"},\"quantity\":1.00,\"unitNetPrice\":1.00,\"discountPercentage\":0.00,\"unitCostPrice\":0.00,\"totalNetAmount\":1.00,\"marginInBaseCurrency\":1.00,\"marginPercentage\":100.00}]," +
                                   "\"date\":\"2024-09-09\",\"currency\":\"DKK\",\"exchangeRate\":100.000000,\"netAmount\":1.000000,\"netAmountInBaseCurrency\":1.00,\"grossAmount\":1.000000,\"grossAmountInBaseCurrency\":1.00,\"marginInBaseCurrency\":1.0000,\"marginPercentage\":100.00,\"vatAmount\":0.000000,\"roundingAmount\":0.00,\"costPriceInBaseCurrency\":0.0000,\"dueDate\":\"2024-09-10\",\"paymentTerms\":{\"paymentTermsNumber\":4,\"daysOfCredit\":1,\"description\":\"Test betalings betingelse\",\"name\":\"99999\",\"paymentTermsType\":\"net\",\"self\":\"https://restapi.e-conomic.com/payment-terms/4\"},\"customer\":{\"customerNumber\":99999,\"self\":\"https://restapi.e-conomic.com/customers/99999\"},\"recipient\":{\"name\":\"Testkunde\",\"address\":\"Dette er en testkunde.\",\"zip\":\"\",\"city\":\"\",\"vatZone\":{\"name\":\"Domestic\",\"vatZoneNumber\":1,\"enabledForCustomer\":true,\"enabledForSupplier\":true,\"self\":\"https://restapi.e-conomic.com/vat-zones/1\"}},\"notes\":{\"heading\":\"#99999 Testkunde\",\"textLine1\":\"xx\"},\"layout\":{\"layoutNumber\":21,\"self\":\"https://restapi.e-conomic.com/layouts/21\"},\"pdf\":{\"download\":\"https://restapi.e-conomic.com/invoices/drafts/485/pdf\"},\"lastUpdated\":\"2024-09-09T20:24:00Z\",\"self\":\"https://restapi.e-conomic.com/invoices/drafts/485\"}";
        var dic = new Dictionary<int, string>
        {
            { 454, response454 },
            { 485, response485 }
        };
        return new MemoryStream(Encoding.UTF8.GetBytes(dic[invoiceNumber]));
    }

    public async Task<Stream> GetBookedInvoices(int skipPages, int pageSize, IInterval<DateTime> dateRange, CancellationToken cancellationToken)
    {
        const string response = "{\"collection\":[" +
                                "{\"bookedInvoiceNumber\":16,\"orderNumber\":17,\"date\":\"2024-01-17\",\"currency\":\"DKK\",\"exchangeRate\":100.000000,\"netAmount\":-866.00,\"netAmountInBaseCurrency\":-866.00,\"grossAmount\":-866.00,\"grossAmountInBaseCurrency\":-866.00,\"vatAmount\":0.00,\"roundingAmount\":0.00,\"remainder\":0.00,\"remainderInBaseCurrency\":0.00,\"dueDate\":\"2024-02-14\",\"paymentTerms\":{\"paymentTermsNumber\":1,\"daysOfCredit\":14,\"name\":\"Lb. md. 14 dage\",\"paymentTermsType\":\"invoiceMonth\",\"self\":\"https://restapi.e-conomic.com/payment-terms/1?date$lte:2024-01-31\"},\"customer\":{\"customerNumber\":1117,\"self\":\"https://restapi.e-conomic.com/customers/1117?date$lte:2024-01-31\"},\"recipient\":{\"name\":\"Torup Landsbycenter af 1995\",\"address\":\"Hågendrupvej 6\",\"zip\":\"3390\",\"city\":\"Hundested\",\"country\":\"Danmark\",\"vatZone\":{\"name\":\"Domestic\",\"vatZoneNumber\":1,\"enabledForCustomer\":true,\"enabledForSupplier\":true,\"self\":\"https://restapi.e-conomic.com/vat-zones/1?date$lte:2024-01-31\"}},\"notes\":{\"heading\":\"Fotokopiering m.m. 2023\"},\"layout\":{\"layoutNumber\":21,\"self\":\"https://restapi.e-conomic.com/layouts/21?date$lte:2024-01-31\"},\"pdf\":{\"download\":\"https://restapi.e-conomic.com/invoices/booked/16/pdf?date$lte:2024-01-31\"},\"sent\":\"https://restapi.e-conomic.com/invoices/booked/16/sent?date$lte:2024-01-31\",\"self\":\"https://restapi.e-conomic.com/invoices/booked/16?date$lte:2024-01-31\"}," +
                                "{\"bookedInvoiceNumber\":18,\"orderNumber\":19,\"date\":\"2024-01-17\",\"currency\":\"DKK\",\"exchangeRate\":100.000000,\"netAmount\":615.00,\"netAmountInBaseCurrency\":615.00,\"grossAmount\":615.00,\"grossAmountInBaseCurrency\":615.00,\"vatAmount\":0.00,\"roundingAmount\":0.00,\"remainder\":0.00,\"remainderInBaseCurrency\":0.00,\"dueDate\":\"2024-02-16\",\"paymentTerms\":{\"paymentTermsNumber\":3,\"daysOfCredit\":30,\"name\":\"30 dage\",\"paymentTermsType\":\"net\",\"self\":\"https://restapi.e-conomic.com/payment-terms/3?date$lte:2024-01-31\"},\"customer\":{\"customerNumber\":1112,\"self\":\"https://restapi.e-conomic.com/customers/1112?date$lte:2024-01-31\"},\"recipient\":{\"name\":\"Kunst i Torup\",\"address\":\"Torupvejen 109\",\"zip\":\"3390\",\"city\":\"Hundested\",\"country\":\"Danmark\",\"vatZone\":{\"name\":\"Domestic\",\"vatZoneNumber\":1,\"enabledForCustomer\":true,\"enabledForSupplier\":true,\"self\":\"https://restapi.e-conomic.com/vat-zones/1?date$lte:2024-01-31\"}},\"notes\":{\"heading\":\"Print og laminering 2023\"},\"layout\":{\"layoutNumber\":21,\"self\":\"https://restapi.e-conomic.com/layouts/21?date$lte:2024-01-31\"},\"pdf\":{\"download\":\"https://restapi.e-conomic.com/invoices/booked/18/pdf?date$lte:2024-01-31\"},\"sent\":\"https://restapi.e-conomic.com/invoices/booked/18/sent?date$lte:2024-01-31\",\"self\":\"https://restapi.e-conomic.com/invoices/booked/18?date$lte:2024-01-31\"}]," +
                                "\"pagination\":{\"skipPages\":0,\"pageSize\":2,\"maxPageSizeAllowed\":1000,\"results\":146,\"resultsWithoutFilter\":177,\"firstPage\":\"https://restapi.e-conomic.com/invoices/booked?skippages=0&pagesize=2&filter=date%24gte%3A2024-01-01&date$lte:2024-01-31\",\"nextPage\":\"https://restapi.e-conomic.com/invoices/booked?skippages=1&pagesize=2&filter=date%24gte%3A2024-01-01&date$lte:2024-01-31\",\"lastPage\":\"https://restapi.e-conomic.com/invoices/booked?skippages=72&pagesize=2&filter=date%24gte%3A2024-01-01&date$lte:2024-01-31\"},\"self\":\"https://restapi.e-conomic.com/invoices/booked?skippages=0&pagesize=2&filter=date%24gte%3A2024-01-01&date$lte:2024-01-31\"}";
        return new MemoryStream(Encoding.UTF8.GetBytes(response));
    }

    public async Task<Stream> GetBookedInvoice(int invoiceNumber, CancellationToken cancellationToken)
    {
        const string response16 = "{\"bookedInvoiceNumber\":16,\"orderNumber\":17,\"date\":\"2024-01-17\",\"currency\":\"DKK\",\"exchangeRate\":100.000000,\"netAmount\":-866.00,\"netAmountInBaseCurrency\":-866.00,\"grossAmount\":-866.00,\"grossAmountInBaseCurrency\":-866.00,\"vatAmount\":0.00,\"roundingAmount\":0.00,\"remainder\":0.00,\"remainderInBaseCurrency\":0.00,\"dueDate\":\"2024-02-14\",\"paymentTerms\":{\"paymentTermsNumber\":1,\"daysOfCredit\":14,\"name\":\"Lb. md. 14 dage\",\"paymentTermsType\":\"invoiceMonth\",\"self\":\"https://restapi.e-conomic.com/payment-terms/1\"},\"customer\":{\"customerNumber\":1117,\"self\":\"https://restapi.e-conomic.com/customers/1117\"},\"recipient\":{\"name\":\"Torup Landsbycenter af 1995\",\"address\":\"Hågendrupvej 6\",\"zip\":\"3390\",\"city\":\"Hundested\",\"country\":\"Danmark\",\"vatZone\":{\"name\":\"Domestic\",\"vatZoneNumber\":1,\"enabledForCustomer\":true,\"enabledForSupplier\":true,\"self\":\"https://restapi.e-conomic.com/vat-zones/1\"}},\"notes\":{\"heading\":\"Fotokopiering m.m. 2023\"},\"layout\":{\"layoutNumber\":21,\"self\":\"https://restapi.e-conomic.com/layouts/21\"},\"pdf\":{\"download\":\"https://restapi.e-conomic.com/invoices/booked/16/pdf\"},\"lines\":[" +
                                  "{\"lineNumber\":1,\"sortKey\":1,\"description\":\"A4 almindelig\",\"quantity\":-757.00,\"unitNetPrice\":1.00,\"discountPercentage\":0.00,\"unitCostPrice\":0.00,\"vatRate\":0.00000000,\"vatAmount\":0.0000,\"totalNetAmount\":-757.00,\"product\":{\"productNumber\":\"14\",\"self\":\"https://restapi.e-conomic.com/products/14\"}}," +
                                  //"{\"lineNumber\":2,\"sortKey\":2,\"description\":\"Laminering A4\",\"quantity\":-3.00,\"unitNetPrice\":3.00,\"discountPercentage\":0.00,\"unitCostPrice\":0.00,\"vatRate\":0.00000000,\"vatAmount\":0.0000,\"totalNetAmount\":-9.00,\"product\":{\"productNumber\":\"18\",\"self\":\"https://restapi.e-conomic.com/products/18\"}}," +
                                  //"{\"lineNumber\":3,\"sortKey\":3,\"description\":\"Printerpapir A4, videresalg\",\"quantity\":-1.00,\"unitNetPrice\":100.00,\"discountPercentage\":0.00,\"unitCostPrice\":0.00,\"vatRate\":0.00000000,\"vatAmount\":0.0000,\"totalNetAmount\":-100.00,\"product\":{\"productNumber\":\"20\",\"self\":\"https://restapi.e-conomic.com/products/20\"}}" +
                                  "],\"sent\":\"https://restapi.e-conomic.com/invoices/booked/16/sent\",\"self\":\"https://restapi.e-conomic.com/invoices/booked/16\"}";
        const string response18 = "{\"bookedInvoiceNumber\":18,\"orderNumber\":19,\"date\":\"2024-01-17\",\"currency\":\"DKK\",\"exchangeRate\":100.000000,\"netAmount\":615.00,\"netAmountInBaseCurrency\":615.00,\"grossAmount\":615.00,\"grossAmountInBaseCurrency\":615.00,\"vatAmount\":0.00,\"roundingAmount\":0.00,\"remainder\":0.00,\"remainderInBaseCurrency\":0.00,\"dueDate\":\"2024-02-16\",\"paymentTerms\":{\"paymentTermsNumber\":3,\"daysOfCredit\":30,\"name\":\"30 dage\",\"paymentTermsType\":\"net\",\"self\":\"https://restapi.e-conomic.com/payment-terms/3\"},\"customer\":{\"customerNumber\":1112,\"self\":\"https://restapi.e-conomic.com/customers/1112\"},\"recipient\":{\"name\":\"Kunst i Torup\",\"address\":\"Torupvejen 109\",\"zip\":\"3390\",\"city\":\"Hundested\",\"country\":\"Danmark\",\"vatZone\":{\"name\":\"Domestic\",\"vatZoneNumber\":1,\"enabledForCustomer\":true,\"enabledForSupplier\":true,\"self\":\"https://restapi.e-conomic.com/vat-zones/1\"}},\"notes\":{\"heading\":\"Print og laminering 2023\"},\"layout\":{\"layoutNumber\":21,\"self\":\"https://restapi.e-conomic.com/layouts/21\"},\"pdf\":{\"download\":\"https://restapi.e-conomic.com/invoices/booked/18/pdf\"},\"lines\":[" +
                                  "{\"lineNumber\":1,\"sortKey\":1,\"description\":\"A4 billede\",\"quantity\":109.00,\"unitNetPrice\":3.00,\"discountPercentage\":0.00,\"unitCostPrice\":0.00,\"vatRate\":0.00000000,\"vatAmount\":0.0000,\"totalNetAmount\":327.00,\"product\":{\"productNumber\":\"15\",\"self\":\"https://restapi.e-conomic.com/products/15\"}}," +
                                  //"{\"lineNumber\":2,\"sortKey\":2,\"description\":\"Laminering A4\",\"quantity\":12.00,\"unitNetPrice\":3.00,\"discountPercentage\":0.00,\"unitCostPrice\":0.00,\"vatRate\":0.00000000,\"vatAmount\":0.0000,\"totalNetAmount\":36.00,\"product\":{\"productNumber\":\"18\",\"self\":\"https://restapi.e-conomic.com/products/18\"}}," +
                                  //"{\"lineNumber\":3,\"sortKey\":3,\"description\":\"A3 billede\",\"quantity\":36.00,\"unitNetPrice\":5.00,\"discountPercentage\":0.00,\"unitCostPrice\":0.00,\"vatRate\":0.00000000,\"vatAmount\":0.0000,\"totalNetAmount\":180.00,\"product\":{\"productNumber\":\"17\",\"self\":\"https://restapi.e-conomic.com/products/17\"}}," +
                                  //"{\"lineNumber\":4,\"sortKey\":4,\"description\":\"Laminering A3\",\"quantity\":12.00,\"unitNetPrice\":6.00,\"discountPercentage\":0.00,\"unitCostPrice\":0.00,\"vatRate\":0.00000000,\"vatAmount\":0.0000,\"totalNetAmount\":72.00,\"product\":{\"productNumber\":\"19\",\"self\":\"https://restapi.e-conomic.com/products/19\"}}" +
                                  "],\"sent\":\"https://restapi.e-conomic.com/invoices/booked/18/sent\",\"self\":\"https://restapi.e-conomic.com/invoices/booked/18\"}";
        var dic = new Dictionary<int, string>
        {
            { 16, response16 },
            { 18, response18 }
        };
        return new MemoryStream(Encoding.UTF8.GetBytes(dic[invoiceNumber]));
    }

    public async Task<Stream> PostInvoice(StringContent content, CancellationToken cancellationToken)
    {
        const string response = "";
        return new MemoryStream(Encoding.UTF8.GetBytes(response));
    }

    public async Task<Stream> GetPaymentTerms(int skipPages, int pageSize, CancellationToken cancellationToken)
    {
        const string response = "{\"collection\":[{\"paymentTermsNumber\":1,\"daysOfCredit\":14,\"name\":\"Lb. md. 14 dage\",\"paymentTermsType\":\"invoiceMonth\",\"self\":\"https://restapi.e-conomic.com/payment-terms/1\"},{\"paymentTermsNumber\":2,\"daysOfCredit\":14,\"name\":\"14 dage\",\"paymentTermsType\":\"net\",\"self\":\"https://restapi.e-conomic.com/payment-terms/2\"},{\"paymentTermsNumber\":3,\"daysOfCredit\":30,\"name\":\"30 dage\",\"paymentTermsType\":\"net\",\"self\":\"https://restapi.e-conomic.com/payment-terms/3\"},{\"paymentTermsNumber\":4,\"daysOfCredit\":1,\"description\":\"Test betalings betingelse\",\"name\":\"99999\",\"paymentTermsType\":\"net\",\"self\":\"https://restapi.e-conomic.com/payment-terms/4\"},{\"paymentTermsNumber\":5,\"daysOfCredit\":8,\"name\":\"8 dage\",\"paymentTermsType\":\"net\",\"self\":\"https://restapi.e-conomic.com/payment-terms/5\"}],\"pagination\":{\"skipPages\":0,\"pageSize\":20,\"maxPageSizeAllowed\":1000,\"results\":5,\"resultsWithoutFilter\":5,\"firstPage\":\"https://restapi.e-conomic.com/payment-terms?skippages=0&pagesize=20\",\"lastPage\":\"https://restapi.e-conomic.com/payment-terms?skippages=0&pagesize=20\"},\"self\":\"https://restapi.e-conomic.com/payment-terms?skippages=0&pagesize=20\"}";
        return new MemoryStream(Encoding.UTF8.GetBytes(response));
    }

    public async Task<Stream> GetProducts(int skipPages, int pageSize, CancellationToken cancellationToken)
    {
        const string response = "{\"collection\":[" +
                                //"{\"productNumber\":\"1\",\"description\":\"Depositum\",\"name\":\"Medlemsindskud\",\"recommendedPrice\":0.00,\"salesPrice\":8900.00,\"barred\":false,\"lastUpdated\":\"2024-09-10T19:36:00Z\",\"productGroup\":{\"productGroupNumber\":8,\"name\":\"medlemsindskud\",\"salesAccounts\":\"https://restapi.e-conomic.com/product-groups/8/sales-accounts\",\"products\":\"https://restapi.e-conomic.com/product-groups/8/products\",\"self\":\"https://restapi.e-conomic.com/product-groups/8\"},\"invoices\":{\"drafts\":\"https://restapi.e-conomic.com/products/1/invoices/drafts\",\"booked\":\"https://restapi.e-conomic.com/products/1/invoices/booked\",\"self\":\"https://restapi.e-conomic.com/products/1/invoices\"},\"pricing\":{\"currencySpecificSalesPrices\":\"https://restapi.e-conomic.com/products/1/pricing/currency-specific-sales-prices\"},\"self\":\"https://restapi.e-conomic.com/products/1\"}," +
                                //"{\"productNumber\":\"2\",\"name\":\"Medlemskontingent pr md.\",\"recommendedPrice\":0.00,\"salesPrice\":250.00,\"barred\":false,\"lastUpdated\":\"2024-03-17T18:40:00Z\",\"productGroup\":{\"productGroupNumber\":1,\"name\":\"Medlemskontingent\",\"salesAccounts\":\"https://restapi.e-conomic.com/product-groups/1/sales-accounts\",\"products\":\"https://restapi.e-conomic.com/product-groups/1/products\",\"self\":\"https://restapi.e-conomic.com/product-groups/1\"},\"unit\":{\"unitNumber\":1,\"name\":\"mdr\",\"products\":\"https://restapi.e-conomic.com/units/1/products\",\"self\":\"https://restapi.e-conomic.com/units/1\"},\"invoices\":{\"drafts\":\"https://restapi.e-conomic.com/products/2/invoices/drafts\",\"booked\":\"https://restapi.e-conomic.com/products/2/invoices/booked\",\"self\":\"https://restapi.e-conomic.com/products/2/invoices\"},\"pricing\":{\"currencySpecificSalesPrices\":\"https://restapi.e-conomic.com/products/2/pricing/currency-specific-sales-prices\"},\"self\":\"https://restapi.e-conomic.com/products/2\"}," +
                                //"{\"productNumber\":\"3\",\"name\":\"Grundejerforeningsbidrag\",\"recommendedPrice\":0.00,\"salesPrice\":6.00,\"barred\":false,\"minimumStock\":0.00,\"lastUpdated\":\"2024-03-17T18:42:00Z\",\"productGroup\":{\"productGroupNumber\":2,\"name\":\"Grundejerforening Dyssekilde\",\"salesAccounts\":\"https://restapi.e-conomic.com/product-groups/2/sales-accounts\",\"products\":\"https://restapi.e-conomic.com/product-groups/2/products\",\"self\":\"https://restapi.e-conomic.com/product-groups/2\"},\"unit\":{\"unitNumber\":3,\"name\":\"m2\",\"products\":\"https://restapi.e-conomic.com/units/3/products\",\"self\":\"https://restapi.e-conomic.com/units/3\"},\"invoices\":{\"drafts\":\"https://restapi.e-conomic.com/products/3/invoices/drafts\",\"booked\":\"https://restapi.e-conomic.com/products/3/invoices/booked\",\"self\":\"https://restapi.e-conomic.com/products/3/invoices\"},\"pricing\":{\"currencySpecificSalesPrices\":\"https://restapi.e-conomic.com/products/3/pricing/currency-specific-sales-prices\"},\"self\":\"https://restapi.e-conomic.com/products/3\"}," +
                                //"{\"productNumber\":\"4\",\"name\":\"Vandafledningsafgift 2023\",\"recommendedPrice\":0.00,\"salesPrice\":56.13,\"barred\":false,\"minimumStock\":0.00,\"lastUpdated\":\"2024-03-11T18:34:00Z\",\"productGroup\":{\"productGroupNumber\":9,\"name\":\"Vandafledningsafgift\",\"salesAccounts\":\"https://restapi.e-conomic.com/product-groups/9/sales-accounts\",\"products\":\"https://restapi.e-conomic.com/product-groups/9/products\",\"self\":\"https://restapi.e-conomic.com/product-groups/9\"},\"unit\":{\"unitNumber\":5,\"name\":\"m3\",\"products\":\"https://restapi.e-conomic.com/units/5/products\",\"self\":\"https://restapi.e-conomic.com/units/5\"},\"invoices\":{\"drafts\":\"https://restapi.e-conomic.com/products/4/invoices/drafts\",\"booked\":\"https://restapi.e-conomic.com/products/4/invoices/booked\",\"self\":\"https://restapi.e-conomic.com/products/4/invoices\"},\"pricing\":{\"currencySpecificSalesPrices\":\"https://restapi.e-conomic.com/products/4/pricing/currency-specific-sales-prices\"},\"self\":\"https://restapi.e-conomic.com/products/4\"}," +
                                //"{\"productNumber\":\"5\",\"name\":\"Vand, videresalg 2023\",\"recommendedPrice\":0.00,\"salesPrice\":56.13,\"barred\":false,\"minimumStock\":0.00,\"lastUpdated\":\"2024-02-23T12:38:00Z\",\"productGroup\":{\"productGroupNumber\":10,\"name\":\"Vand, videresalg\",\"salesAccounts\":\"https://restapi.e-conomic.com/product-groups/10/sales-accounts\",\"products\":\"https://restapi.e-conomic.com/product-groups/10/products\",\"self\":\"https://restapi.e-conomic.com/product-groups/10\"},\"unit\":{\"unitNumber\":5,\"name\":\"m3\",\"products\":\"https://restapi.e-conomic.com/units/5/products\",\"self\":\"https://restapi.e-conomic.com/units/5\"},\"invoices\":{\"drafts\":\"https://restapi.e-conomic.com/products/5/invoices/drafts\",\"booked\":\"https://restapi.e-conomic.com/products/5/invoices/booked\",\"self\":\"https://restapi.e-conomic.com/products/5/invoices\"},\"pricing\":{\"currencySpecificSalesPrices\":\"https://restapi.e-conomic.com/products/5/pricing/currency-specific-sales-prices\"},\"self\":\"https://restapi.e-conomic.com/products/5\"}," +
                                //"{\"productNumber\":\"6\",\"name\":\"Elektricitet videresalg 2023\",\"recommendedPrice\":0.00,\"salesPrice\":3.05,\"barred\":false,\"minimumStock\":0.00,\"lastUpdated\":\"2024-09-10T19:36:00Z\",\"productGroup\":{\"productGroupNumber\":11,\"name\":\"El videresalg\",\"salesAccounts\":\"https://restapi.e-conomic.com/product-groups/11/sales-accounts\",\"products\":\"https://restapi.e-conomic.com/product-groups/11/products\",\"self\":\"https://restapi.e-conomic.com/product-groups/11\"},\"invoices\":{\"drafts\":\"https://restapi.e-conomic.com/products/6/invoices/drafts\",\"booked\":\"https://restapi.e-conomic.com/products/6/invoices/booked\",\"self\":\"https://restapi.e-conomic.com/products/6/invoices\"},\"pricing\":{\"currencySpecificSalesPrices\":\"https://restapi.e-conomic.com/products/6/pricing/currency-specific-sales-prices\"},\"self\":\"https://restapi.e-conomic.com/products/6\"}," +
                                //"{\"productNumber\":\"7\",\"name\":\"Erhvervsleje\",\"recommendedPrice\":0.00,\"salesPrice\":21.31,\"barred\":false,\"minimumStock\":0.00,\"lastUpdated\":\"2024-03-24T20:06:00Z\",\"productGroup\":{\"productGroupNumber\":3,\"name\":\"Erhvervsleje\",\"salesAccounts\":\"https://restapi.e-conomic.com/product-groups/3/sales-accounts\",\"products\":\"https://restapi.e-conomic.com/product-groups/3/products\",\"self\":\"https://restapi.e-conomic.com/product-groups/3\"},\"invoices\":{\"drafts\":\"https://restapi.e-conomic.com/products/7/invoices/drafts\",\"booked\":\"https://restapi.e-conomic.com/products/7/invoices/booked\",\"self\":\"https://restapi.e-conomic.com/products/7/invoices\"},\"pricing\":{\"currencySpecificSalesPrices\":\"https://restapi.e-conomic.com/products/7/pricing/currency-specific-sales-prices\"},\"self\":\"https://restapi.e-conomic.com/products/7\"}," +
                                //"{\"productNumber\":\"8\",\"name\":\"Særaftale medlemsindskud\",\"barred\":false,\"minimumStock\":0.00,\"lastUpdated\":\"2023-10-17T11:34:00Z\",\"productGroup\":{\"productGroupNumber\":14,\"name\":\"Særaftale medlemsindskud\",\"salesAccounts\":\"https://restapi.e-conomic.com/product-groups/14/sales-accounts\",\"products\":\"https://restapi.e-conomic.com/product-groups/14/products\",\"self\":\"https://restapi.e-conomic.com/product-groups/14\"},\"invoices\":{\"drafts\":\"https://restapi.e-conomic.com/products/8/invoices/drafts\",\"booked\":\"https://restapi.e-conomic.com/products/8/invoices/booked\",\"self\":\"https://restapi.e-conomic.com/products/8/invoices\"},\"pricing\":{\"currencySpecificSalesPrices\":\"https://restapi.e-conomic.com/products/8/pricing/currency-specific-sales-prices\"},\"self\":\"https://restapi.e-conomic.com/products/8\"}," +
                                //"{\"productNumber\":\"9\",\"name\":\"Tilkøb m2\",\"recommendedPrice\":0.00,\"salesPrice\":2500.00,\"barred\":false,\"minimumStock\":0.00,\"lastUpdated\":\"2024-09-10T19:36:00Z\",\"productGroup\":{\"productGroupNumber\":7,\"name\":\"Tilkøb m2\",\"salesAccounts\":\"https://restapi.e-conomic.com/product-groups/7/sales-accounts\",\"products\":\"https://restapi.e-conomic.com/product-groups/7/products\",\"self\":\"https://restapi.e-conomic.com/product-groups/7\"},\"unit\":{\"unitNumber\":3,\"name\":\"m2\",\"products\":\"https://restapi.e-conomic.com/units/3/products\",\"self\":\"https://restapi.e-conomic.com/units/3\"},\"invoices\":{\"drafts\":\"https://restapi.e-conomic.com/products/9/invoices/drafts\",\"booked\":\"https://restapi.e-conomic.com/products/9/invoices/booked\",\"self\":\"https://restapi.e-conomic.com/products/9/invoices\"},\"pricing\":{\"currencySpecificSalesPrices\":\"https://restapi.e-conomic.com/products/9/pricing/currency-specific-sales-prices\"},\"self\":\"https://restapi.e-conomic.com/products/9\"}," +
                                //"{\"productNumber\":\"10\",\"name\":\"Markleje\",\"recommendedPrice\":0.00,\"salesPrice\":0.50,\"barred\":false,\"lastUpdated\":\"2024-09-10T19:36:00Z\",\"productGroup\":{\"productGroupNumber\":4,\"name\":\"Landbrugsjord, Nyttehaver, grøntkule o.lign., Leje\",\"salesAccounts\":\"https://restapi.e-conomic.com/product-groups/4/sales-accounts\",\"products\":\"https://restapi.e-conomic.com/product-groups/4/products\",\"self\":\"https://restapi.e-conomic.com/product-groups/4\"},\"unit\":{\"unitNumber\":3,\"name\":\"m2\",\"products\":\"https://restapi.e-conomic.com/units/3/products\",\"self\":\"https://restapi.e-conomic.com/units/3\"},\"invoices\":{\"drafts\":\"https://restapi.e-conomic.com/products/10/invoices/drafts\",\"booked\":\"https://restapi.e-conomic.com/products/10/invoices/booked\",\"self\":\"https://restapi.e-conomic.com/products/10/invoices\"},\"pricing\":{\"currencySpecificSalesPrices\":\"https://restapi.e-conomic.com/products/10/pricing/currency-specific-sales-prices\"},\"self\":\"https://restapi.e-conomic.com/products/10\"}," +
                                //"{\"productNumber\":\"13\",\"name\":\"Rundvisning\",\"recommendedPrice\":0.00,\"salesPrice\":1000.00,\"barred\":false,\"lastUpdated\":\"2024-09-10T19:36:00Z\",\"productGroup\":{\"productGroupNumber\":13,\"name\":\"Rundvisning\",\"salesAccounts\":\"https://restapi.e-conomic.com/product-groups/13/sales-accounts\",\"products\":\"https://restapi.e-conomic.com/product-groups/13/products\",\"self\":\"https://restapi.e-conomic.com/product-groups/13\"},\"unit\":{\"unitNumber\":2,\"name\":\"stk\",\"products\":\"https://restapi.e-conomic.com/units/2/products\",\"self\":\"https://restapi.e-conomic.com/units/2\"},\"invoices\":{\"drafts\":\"https://restapi.e-conomic.com/products/13/invoices/drafts\",\"booked\":\"https://restapi.e-conomic.com/products/13/invoices/booked\",\"self\":\"https://restapi.e-conomic.com/products/13/invoices\"},\"pricing\":{\"currencySpecificSalesPrices\":\"https://restapi.e-conomic.com/products/13/pricing/currency-specific-sales-prices\"},\"self\":\"https://restapi.e-conomic.com/products/13\"}," +
                                "{\"productNumber\":\"14\",\"name\":\"A4 almindelig\",\"recommendedPrice\":0.00,\"salesPrice\":1.00,\"barred\":false,\"minimumStock\":0.00,\"lastUpdated\":\"2024-02-29T13:39:00Z\",\"productGroup\":{\"productGroupNumber\":6,\"name\":\"Fotokopiering o.lign. videresalg\",\"salesAccounts\":\"https://restapi.e-conomic.com/product-groups/6/sales-accounts\",\"products\":\"https://restapi.e-conomic.com/product-groups/6/products\",\"self\":\"https://restapi.e-conomic.com/product-groups/6\"},\"invoices\":{\"drafts\":\"https://restapi.e-conomic.com/products/14/invoices/drafts\",\"booked\":\"https://restapi.e-conomic.com/products/14/invoices/booked\",\"self\":\"https://restapi.e-conomic.com/products/14/invoices\"},\"pricing\":{\"currencySpecificSalesPrices\":\"https://restapi.e-conomic.com/products/14/pricing/currency-specific-sales-prices\"},\"self\":\"https://restapi.e-conomic.com/products/14\"}," +
                                "{\"productNumber\":\"15\",\"name\":\"A4 billede\",\"recommendedPrice\":0.00,\"salesPrice\":3.00,\"barred\":false,\"minimumStock\":0.00,\"lastUpdated\":\"2024-07-26T10:54:00Z\",\"productGroup\":{\"productGroupNumber\":6,\"name\":\"Fotokopiering o.lign. videresalg\",\"salesAccounts\":\"https://restapi.e-conomic.com/product-groups/6/sales-accounts\",\"products\":\"https://restapi.e-conomic.com/product-groups/6/products\",\"self\":\"https://restapi.e-conomic.com/product-groups/6\"},\"invoices\":{\"drafts\":\"https://restapi.e-conomic.com/products/15/invoices/drafts\",\"booked\":\"https://restapi.e-conomic.com/products/15/invoices/booked\",\"self\":\"https://restapi.e-conomic.com/products/15/invoices\"},\"pricing\":{\"currencySpecificSalesPrices\":\"https://restapi.e-conomic.com/products/15/pricing/currency-specific-sales-prices\"},\"self\":\"https://restapi.e-conomic.com/products/15\"}," +
                                //"{\"productNumber\":\"16\",\"name\":\"A3 almindelig\",\"recommendedPrice\":0.00,\"salesPrice\":2.00,\"barred\":false,\"minimumStock\":0.00,\"lastUpdated\":\"2024-02-29T13:39:00Z\",\"productGroup\":{\"productGroupNumber\":6,\"name\":\"Fotokopiering o.lign. videresalg\",\"salesAccounts\":\"https://restapi.e-conomic.com/product-groups/6/sales-accounts\",\"products\":\"https://restapi.e-conomic.com/product-groups/6/products\",\"self\":\"https://restapi.e-conomic.com/product-groups/6\"},\"invoices\":{\"drafts\":\"https://restapi.e-conomic.com/products/16/invoices/drafts\",\"booked\":\"https://restapi.e-conomic.com/products/16/invoices/booked\",\"self\":\"https://restapi.e-conomic.com/products/16/invoices\"},\"pricing\":{\"currencySpecificSalesPrices\":\"https://restapi.e-conomic.com/products/16/pricing/currency-specific-sales-prices\"},\"self\":\"https://restapi.e-conomic.com/products/16\"}," +
                                //"{\"productNumber\":\"17\",\"name\":\"A3 billede\",\"recommendedPrice\":0.00,\"salesPrice\":5.00,\"barred\":false,\"minimumStock\":0.00,\"lastUpdated\":\"2024-07-26T10:54:00Z\",\"productGroup\":{\"productGroupNumber\":6,\"name\":\"Fotokopiering o.lign. videresalg\",\"salesAccounts\":\"https://restapi.e-conomic.com/product-groups/6/sales-accounts\",\"products\":\"https://restapi.e-conomic.com/product-groups/6/products\",\"self\":\"https://restapi.e-conomic.com/product-groups/6\"},\"invoices\":{\"drafts\":\"https://restapi.e-conomic.com/products/17/invoices/drafts\",\"booked\":\"https://restapi.e-conomic.com/products/17/invoices/booked\",\"self\":\"https://restapi.e-conomic.com/products/17/invoices\"},\"pricing\":{\"currencySpecificSalesPrices\":\"https://restapi.e-conomic.com/products/17/pricing/currency-specific-sales-prices\"},\"self\":\"https://restapi.e-conomic.com/products/17\"}," +
                                //"{\"productNumber\":\"18\",\"name\":\"Laminering A4\",\"recommendedPrice\":0.00,\"salesPrice\":3.00,\"barred\":false,\"minimumStock\":0.00,\"lastUpdated\":\"2024-02-29T13:39:00Z\",\"productGroup\":{\"productGroupNumber\":6,\"name\":\"Fotokopiering o.lign. videresalg\",\"salesAccounts\":\"https://restapi.e-conomic.com/product-groups/6/sales-accounts\",\"products\":\"https://restapi.e-conomic.com/product-groups/6/products\",\"self\":\"https://restapi.e-conomic.com/product-groups/6\"},\"invoices\":{\"drafts\":\"https://restapi.e-conomic.com/products/18/invoices/drafts\",\"booked\":\"https://restapi.e-conomic.com/products/18/invoices/booked\",\"self\":\"https://restapi.e-conomic.com/products/18/invoices\"},\"pricing\":{\"currencySpecificSalesPrices\":\"https://restapi.e-conomic.com/products/18/pricing/currency-specific-sales-prices\"},\"self\":\"https://restapi.e-conomic.com/products/18\"}," +
                                //"{\"productNumber\":\"19\",\"name\":\"Laminering A3\",\"recommendedPrice\":0.00,\"salesPrice\":6.00,\"barred\":false,\"minimumStock\":0.00,\"lastUpdated\":\"2024-02-29T13:39:00Z\",\"productGroup\":{\"productGroupNumber\":6,\"name\":\"Fotokopiering o.lign. videresalg\",\"salesAccounts\":\"https://restapi.e-conomic.com/product-groups/6/sales-accounts\",\"products\":\"https://restapi.e-conomic.com/product-groups/6/products\",\"self\":\"https://restapi.e-conomic.com/product-groups/6\"},\"invoices\":{\"drafts\":\"https://restapi.e-conomic.com/products/19/invoices/drafts\",\"booked\":\"https://restapi.e-conomic.com/products/19/invoices/booked\",\"self\":\"https://restapi.e-conomic.com/products/19/invoices\"},\"pricing\":{\"currencySpecificSalesPrices\":\"https://restapi.e-conomic.com/products/19/pricing/currency-specific-sales-prices\"},\"self\":\"https://restapi.e-conomic.com/products/19\"}," +
                                //"{\"productNumber\":\"20\",\"description\":\"1 pakke\",\"name\":\"Printerpapir A4, videresalg\",\"recommendedPrice\":0.00,\"salesPrice\":100.00,\"barred\":false,\"minimumStock\":0.00,\"lastUpdated\":\"2024-09-10T19:27:00Z\",\"productGroup\":{\"productGroupNumber\":6,\"name\":\"Fotokopiering o.lign. videresalg\",\"salesAccounts\":\"https://restapi.e-conomic.com/product-groups/6/sales-accounts\",\"products\":\"https://restapi.e-conomic.com/product-groups/6/products\",\"self\":\"https://restapi.e-conomic.com/product-groups/6\"},\"invoices\":{\"drafts\":\"https://restapi.e-conomic.com/products/20/invoices/drafts\",\"booked\":\"https://restapi.e-conomic.com/products/20/invoices/booked\",\"self\":\"https://restapi.e-conomic.com/products/20/invoices\"},\"pricing\":{\"currencySpecificSalesPrices\":\"https://restapi.e-conomic.com/products/20/pricing/currency-specific-sales-prices\"},\"self\":\"https://restapi.e-conomic.com/products/20\"}," +
                                //"{\"productNumber\":\"21\",\"name\":\"Leje af Markskur\",\"recommendedPrice\":0.00,\"salesPrice\":12000.00,\"barred\":false,\"lastUpdated\":\"2024-09-10T19:36:00Z\",\"productGroup\":{\"productGroupNumber\":3,\"name\":\"Erhvervsleje\",\"salesAccounts\":\"https://restapi.e-conomic.com/product-groups/3/sales-accounts\",\"products\":\"https://restapi.e-conomic.com/product-groups/3/products\",\"self\":\"https://restapi.e-conomic.com/product-groups/3\"},\"invoices\":{\"drafts\":\"https://restapi.e-conomic.com/products/21/invoices/drafts\",\"booked\":\"https://restapi.e-conomic.com/products/21/invoices/booked\",\"self\":\"https://restapi.e-conomic.com/products/21/invoices\"},\"pricing\":{\"currencySpecificSalesPrices\":\"https://restapi.e-conomic.com/products/21/pricing/currency-specific-sales-prices\"},\"self\":\"https://restapi.e-conomic.com/products/21\"}," +
                                //"{\"productNumber\":\"22\",\"description\":\"Grundskyld og dækningsafgift fra Vurderingsstyrelsen.\",\"name\":\"Grundskyld og dækningsafgift\",\"recommendedPrice\":0.00,\"salesPrice\":0.00,\"barred\":false,\"minimumStock\":0.00,\"lastUpdated\":\"2024-03-10T20:58:00Z\",\"productGroup\":{\"productGroupNumber\":15,\"name\":\"Udlæg for Vurderingsstyrelsen\",\"salesAccounts\":\"https://restapi.e-conomic.com/product-groups/15/sales-accounts\",\"products\":\"https://restapi.e-conomic.com/product-groups/15/products\",\"self\":\"https://restapi.e-conomic.com/product-groups/15\"},\"invoices\":{\"drafts\":\"https://restapi.e-conomic.com/products/22/invoices/drafts\",\"booked\":\"https://restapi.e-conomic.com/products/22/invoices/booked\",\"self\":\"https://restapi.e-conomic.com/products/22/invoices\"},\"pricing\":{\"currencySpecificSalesPrices\":\"https://restapi.e-conomic.com/products/22/pricing/currency-specific-sales-prices\"},\"self\":\"https://restapi.e-conomic.com/products/22\"}," +
                                //"{\"productNumber\":\"23\",\"description\":\"Tab på debitorer\",\"name\":\"Tab på debitorer\",\"salesPrice\":-1.00,\"barred\":false,\"minimumStock\":0.00,\"lastUpdated\":\"2024-03-05T12:19:00Z\",\"productGroup\":{\"productGroupNumber\":16,\"name\":\"Tab på debitorer\",\"salesAccounts\":\"https://restapi.e-conomic.com/product-groups/16/sales-accounts\",\"products\":\"https://restapi.e-conomic.com/product-groups/16/products\",\"self\":\"https://restapi.e-conomic.com/product-groups/16\"},\"invoices\":{\"drafts\":\"https://restapi.e-conomic.com/products/23/invoices/drafts\",\"booked\":\"https://restapi.e-conomic.com/products/23/invoices/booked\",\"self\":\"https://restapi.e-conomic.com/products/23/invoices\"},\"pricing\":{\"currencySpecificSalesPrices\":\"https://restapi.e-conomic.com/products/23/pricing/currency-specific-sales-prices\"},\"self\":\"https://restapi.e-conomic.com/products/23\"}," +
                                //"{\"productNumber\":\"24\",\"name\":\"Jordvarme driftsbidrag\",\"recommendedPrice\":0.00,\"salesPrice\":240.00,\"barred\":false,\"minimumStock\":0.00,\"lastUpdated\":\"2024-03-15T18:42:00Z\",\"productGroup\":{\"productGroupNumber\":12,\"name\":\"Jordvarme\",\"salesAccounts\":\"https://restapi.e-conomic.com/product-groups/12/sales-accounts\",\"products\":\"https://restapi.e-conomic.com/product-groups/12/products\",\"self\":\"https://restapi.e-conomic.com/product-groups/12\"},\"unit\":{\"unitNumber\":7,\"name\":\"kW\",\"products\":\"https://restapi.e-conomic.com/units/7/products\",\"self\":\"https://restapi.e-conomic.com/units/7\"},\"invoices\":{\"drafts\":\"https://restapi.e-conomic.com/products/24/invoices/drafts\",\"booked\":\"https://restapi.e-conomic.com/products/24/invoices/booked\",\"self\":\"https://restapi.e-conomic.com/products/24/invoices\"},\"pricing\":{\"currencySpecificSalesPrices\":\"https://restapi.e-conomic.com/products/24/pricing/currency-specific-sales-prices\"},\"self\":\"https://restapi.e-conomic.com/products/24\"}," +
                                //"{\"productNumber\":\"25\",\"name\":\"Nyttehave\",\"recommendedPrice\":0.00,\"salesPrice\":1.00,\"barred\":false,\"minimumStock\":0.00,\"lastUpdated\":\"2024-03-17T18:23:00Z\",\"productGroup\":{\"productGroupNumber\":4,\"name\":\"Landbrugsjord, Nyttehaver, grøntkule o.lign., Leje\",\"salesAccounts\":\"https://restapi.e-conomic.com/product-groups/4/sales-accounts\",\"products\":\"https://restapi.e-conomic.com/product-groups/4/products\",\"self\":\"https://restapi.e-conomic.com/product-groups/4\"},\"unit\":{\"unitNumber\":3,\"name\":\"m2\",\"products\":\"https://restapi.e-conomic.com/units/3/products\",\"self\":\"https://restapi.e-conomic.com/units/3\"},\"invoices\":{\"drafts\":\"https://restapi.e-conomic.com/products/25/invoices/drafts\",\"booked\":\"https://restapi.e-conomic.com/products/25/invoices/booked\",\"self\":\"https://restapi.e-conomic.com/products/25/invoices\"},\"pricing\":{\"currencySpecificSalesPrices\":\"https://restapi.e-conomic.com/products/25/pricing/currency-specific-sales-prices\"},\"self\":\"https://restapi.e-conomic.com/products/25\"}," +
                                //"{\"productNumber\":\"26\",\"name\":\"Leje Jordkælder\",\"barred\":false,\"minimumStock\":0.00,\"lastUpdated\":\"2024-03-17T19:10:00Z\",\"productGroup\":{\"productGroupNumber\":4,\"name\":\"Landbrugsjord, Nyttehaver, grøntkule o.lign., Leje\",\"salesAccounts\":\"https://restapi.e-conomic.com/product-groups/4/sales-accounts\",\"products\":\"https://restapi.e-conomic.com/product-groups/4/products\",\"self\":\"https://restapi.e-conomic.com/product-groups/4\"},\"invoices\":{\"drafts\":\"https://restapi.e-conomic.com/products/26/invoices/drafts\",\"booked\":\"https://restapi.e-conomic.com/products/26/invoices/booked\",\"self\":\"https://restapi.e-conomic.com/products/26/invoices\"},\"pricing\":{\"currencySpecificSalesPrices\":\"https://restapi.e-conomic.com/products/26/pricing/currency-specific-sales-prices\"},\"self\":\"https://restapi.e-conomic.com/products/26\"}," +
                                //"{\"productNumber\":\"27\",\"name\":\"Medlemskontingent\",\"recommendedPrice\":0.00,\"salesPrice\":3000.00,\"barred\":false,\"minimumStock\":0.00,\"lastUpdated\":\"2024-03-17T18:42:00Z\",\"productGroup\":{\"productGroupNumber\":1,\"name\":\"Medlemskontingent\",\"salesAccounts\":\"https://restapi.e-conomic.com/product-groups/1/sales-accounts\",\"products\":\"https://restapi.e-conomic.com/product-groups/1/products\",\"self\":\"https://restapi.e-conomic.com/product-groups/1\"},\"unit\":{\"unitNumber\":6,\"name\":\"år\",\"products\":\"https://restapi.e-conomic.com/units/6/products\",\"self\":\"https://restapi.e-conomic.com/units/6\"},\"invoices\":{\"drafts\":\"https://restapi.e-conomic.com/products/27/invoices/drafts\",\"booked\":\"https://restapi.e-conomic.com/products/27/invoices/booked\",\"self\":\"https://restapi.e-conomic.com/products/27/invoices\"},\"pricing\":{\"currencySpecificSalesPrices\":\"https://restapi.e-conomic.com/products/27/pricing/currency-specific-sales-prices\"},\"self\":\"https://restapi.e-conomic.com/products/27\"}," +
                                //"{\"productNumber\":\"28\",\"name\":\"Medlemskontingent udeboende\",\"recommendedPrice\":0.00,\"salesPrice\":1440.00,\"barred\":false,\"minimumStock\":0.00,\"lastUpdated\":\"2024-03-17T18:45:00Z\",\"productGroup\":{\"productGroupNumber\":1,\"name\":\"Medlemskontingent\",\"salesAccounts\":\"https://restapi.e-conomic.com/product-groups/1/sales-accounts\",\"products\":\"https://restapi.e-conomic.com/product-groups/1/products\",\"self\":\"https://restapi.e-conomic.com/product-groups/1\"},\"unit\":{\"unitNumber\":6,\"name\":\"år\",\"products\":\"https://restapi.e-conomic.com/units/6/products\",\"self\":\"https://restapi.e-conomic.com/units/6\"},\"invoices\":{\"drafts\":\"https://restapi.e-conomic.com/products/28/invoices/drafts\",\"booked\":\"https://restapi.e-conomic.com/products/28/invoices/booked\",\"self\":\"https://restapi.e-conomic.com/products/28/invoices\"},\"pricing\":{\"currencySpecificSalesPrices\":\"https://restapi.e-conomic.com/products/28/pricing/currency-specific-sales-prices\"},\"self\":\"https://restapi.e-conomic.com/products/28\"}," +
                                "{\"productNumber\":\"99999\",\"description\":\"Salgsvare 99.999\",\"name\":\"Testvare\",\"costPrice\":0.00,\"recommendedPrice\":1.00,\"salesPrice\":1.00,\"barred\":false,\"minimumStock\":0.00,\"lastUpdated\":\"2024-07-26T12:38:00Z\",\"productGroup\":{\"productGroupNumber\":99999,\"name\":\"Test varegruppe\",\"salesAccounts\":\"https://restapi.e-conomic.com/product-groups/99999/sales-accounts\",\"products\":\"https://restapi.e-conomic.com/product-groups/99999/products\",\"self\":\"https://restapi.e-conomic.com/product-groups/99999\"},\"unit\":{\"unitNumber\":1,\"name\":\"mdr\",\"products\":\"https://restapi.e-conomic.com/units/1/products\",\"self\":\"https://restapi.e-conomic.com/units/1\"},\"invoices\":{\"drafts\":\"https://restapi.e-conomic.com/products/99999/invoices/drafts\",\"booked\":\"https://restapi.e-conomic.com/products/99999/invoices/booked\",\"self\":\"https://restapi.e-conomic.com/products/99999/invoices\"},\"pricing\":{\"currencySpecificSalesPrices\":\"https://restapi.e-conomic.com/products/99999/pricing/currency-specific-sales-prices\"},\"self\":\"https://restapi.e-conomic.com/products/99999\"}],\"pagination\":{\"skipPages\":0,\"pageSize\":200,\"maxPageSizeAllowed\":1000,\"results\":27,\"resultsWithoutFilter\":27,\"firstPage\":\"https://restapi.e-conomic.com/products?skippages=0&pagesize=200\",\"lastPage\":\"https://restapi.e-conomic.com/products?skippages=0&pagesize=200\"},\"metaData\":{\"create\":{\"description\":\"Create a new product\",\"href\":\"https://restapi.e-conomic.com/products?skippages=0&pagesize=200\",\"httpMethod\":\"post\"}},\"self\":\"https://restapi.e-conomic.com/products?skippages=0&pagesize=200\"}";
        return new MemoryStream(Encoding.UTF8.GetBytes(response));
    }

    public async Task<Stream> GetProduct(int productNumber, CancellationToken cancellationToken)
    {
        const string response99999 = "{\"productNumber\":\"99999\",\"description\":\"Salgsvare 99.999\",\"name\":\"Testvare\",\"costPrice\":0.00,\"recommendedPrice\":1.00,\"salesPrice\":1.00,\"barred\":false,\"minimumStock\":0.00,\"lastUpdated\":\"2024-07-26T12:38:00Z\",\"productGroup\":{\"productGroupNumber\":99999,\"name\":\"Test varegruppe\",\"salesAccounts\":\"https://restapi.e-conomic.com/product-groups/99999/sales-accounts\",\"products\":\"https://restapi.e-conomic.com/product-groups/99999/products\",\"self\":\"https://restapi.e-conomic.com/product-groups/99999\"},\"unit\":{\"unitNumber\":1,\"name\":\"mdr\",\"products\":\"https://restapi.e-conomic.com/units/1/products\",\"self\":\"https://restapi.e-conomic.com/units/1\"},\"invoices\":{\"drafts\":\"https://restapi.e-conomic.com/products/99999/invoices/drafts\",\"booked\":\"https://restapi.e-conomic.com/products/99999/invoices/booked\",\"self\":\"https://restapi.e-conomic.com/products/99999/invoices\"},\"pricing\":{\"currencySpecificSalesPrices\":\"https://restapi.e-conomic.com/products/99999/pricing/currency-specific-sales-prices\"},\"metaData\":{\"delete\":{\"description\":\"Delete this product.\",\"href\":\"https://restapi.e-conomic.com/products/99999\",\"httpMethod\":\"delete\"},\"replace\":{\"description\":\"Replace this product.\",\"href\":\"https://restapi.e-conomic.com/products/99999\",\"httpMethod\":\"put\"}},\"self\":\"https://restapi.e-conomic.com/products/99999\"}";
        const string response14 = "{\"productNumber\":\"14\",\"name\":\"A4 almindelig\",\"recommendedPrice\":0.00,\"salesPrice\":1.00,\"barred\":false,\"minimumStock\":0.00,\"lastUpdated\":\"2024-02-29T13:39:00Z\",\"productGroup\":{\"productGroupNumber\":6,\"name\":\"Fotokopiering o.lign. videresalg\",\"salesAccounts\":\"https://restapi.e-conomic.com/product-groups/6/sales-accounts\",\"products\":\"https://restapi.e-conomic.com/product-groups/6/products\",\"self\":\"https://restapi.e-conomic.com/product-groups/6\"},\"invoices\":{\"drafts\":\"https://restapi.e-conomic.com/products/14/invoices/drafts\",\"booked\":\"https://restapi.e-conomic.com/products/14/invoices/booked\",\"self\":\"https://restapi.e-conomic.com/products/14/invoices\"},\"pricing\":{\"currencySpecificSalesPrices\":\"https://restapi.e-conomic.com/products/14/pricing/currency-specific-sales-prices\"},\"metaData\":{\"delete\":{\"description\":\"Delete this product.\",\"href\":\"https://restapi.e-conomic.com/products/14\",\"httpMethod\":\"delete\"},\"replace\":{\"description\":\"Replace this product.\",\"href\":\"https://restapi.e-conomic.com/products/14\",\"httpMethod\":\"put\"}},\"self\":\"https://restapi.e-conomic.com/products/14\"}";
        const string response15 = "{\"productNumber\":\"15\",\"name\":\"A4 billede\",\"recommendedPrice\":0.00,\"salesPrice\":3.00,\"barred\":false,\"minimumStock\":0.00,\"lastUpdated\":\"2024-07-26T10:54:00Z\",\"productGroup\":{\"productGroupNumber\":6,\"name\":\"Fotokopiering o.lign. videresalg\",\"salesAccounts\":\"https://restapi.e-conomic.com/product-groups/6/sales-accounts\",\"products\":\"https://restapi.e-conomic.com/product-groups/6/products\",\"self\":\"https://restapi.e-conomic.com/product-groups/6\"},\"invoices\":{\"drafts\":\"https://restapi.e-conomic.com/products/15/invoices/drafts\",\"booked\":\"https://restapi.e-conomic.com/products/15/invoices/booked\",\"self\":\"https://restapi.e-conomic.com/products/15/invoices\"},\"pricing\":{\"currencySpecificSalesPrices\":\"https://restapi.e-conomic.com/products/15/pricing/currency-specific-sales-prices\"},\"metaData\":{\"delete\":{\"description\":\"Delete this product.\",\"href\":\"https://restapi.e-conomic.com/products/15\",\"httpMethod\":\"delete\"},\"replace\":{\"description\":\"Replace this product.\",\"href\":\"https://restapi.e-conomic.com/products/15\",\"httpMethod\":\"put\"}},\"self\":\"https://restapi.e-conomic.com/products/15\"}";
        var dic = new Dictionary<int, string>
        {
            { 99999, response99999 },
            { 14, response14 },
            { 15, response15 }
        };

        return new MemoryStream(Encoding.UTF8.GetBytes(dic[productNumber]));
    }
}
